/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.freeboxos.ftb.client;

import fr.freeboxos.ftb.metier.MetierFactory;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alan
 */
public class MainIhm extends javax.swing.JFrame {

    /**
     * Creates new form MainIhm
     *
     * @throws java.lang.Exception
     */
    public MainIhm() throws Exception {
        super("Inventaire informatique");
        initComponents();
        //this.setSize(1920, 1080);
        this.setLocationRelativeTo(null);
        this.jLabel_cpu.setText(String.valueOf(MetierFactory.getProcesseurService().getCount()));
        this.jLabel_autre.setText(String.valueOf(MetierFactory.getAutreService().getCount()));
        this.jLabel_cable.setText(String.valueOf(MetierFactory.getCableService().getCount()));
        this.jLabel_hdd.setText(String.valueOf(MetierFactory.getHDDService().getCount()));
        this.jLabel_ram.setText(String.valueOf(MetierFactory.getMemoireService().getCount()));
        this.jLabel_prixTotal.setText("Le prix totale est de ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel_cpu = new javax.swing.JLabel();
        jLabel_ram = new javax.swing.JLabel();
        jLabel_hdd = new javax.swing.JLabel();
        jLabel_cable = new javax.swing.JLabel();
        jLabel_autre = new javax.swing.JLabel();
        jLabel_prixTotal = new javax.swing.JLabel();
        jButton_Quitter = new javax.swing.JButton();
        jButtonUtilisateur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inventaire");

        jButton1.setText("Processeur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Memoire");

        jButton3.setText("Disque dur");

        jButton4.setText("Cable");

        jButton5.setText("Autre");

        jLabel_cpu.setText("jLabel2");

        jLabel_ram.setText("jLabel3");

        jLabel_hdd.setText("jLabel4");

        jLabel_cable.setText("jLabel5");

        jLabel_autre.setText("jLabel6");

        jLabel_prixTotal.setText("jLabel7");

        jButton_Quitter.setText("Quitter");
        jButton_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuitterActionPerformed(evt);
            }
        });

        jButtonUtilisateur.setText("Utilisateur");
        jButtonUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUtilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Quitter)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel_cpu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel_ram))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel_hdd)
                            .addComponent(jLabel_prixTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jLabel_cable))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_autre)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonUtilisateur))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cpu)
                    .addComponent(jLabel_ram)
                    .addComponent(jLabel_hdd)
                    .addComponent(jLabel_cable)
                    .addComponent(jLabel_autre))
                .addGap(77, 77, 77)
                .addComponent(jLabel_prixTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonUtilisateur)
                .addGap(7, 7, 7)
                .addComponent(jButton_Quitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuitterActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_QuitterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ProcesseurIHM processeurIHM = null;
        try {
            processeurIHM = new ProcesseurIHM(this, true);
        } catch (Exception ex) {
            Logger.getLogger(MainIhm.class.getName()).log(Level.SEVERE, null, ex);
        }
        processeurIHM.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUtilisateurActionPerformed
        AdministrateurIHM administrateurIHM = null;
        try {
            administrateurIHM = new AdministrateurIHM(this, true);
        } catch (Exception e) {
            Logger.getLogger(MainIhm.class.getName()).log(Level.SEVERE, null, e);
        }
        administrateurIHM.setVisible(true);
    }//GEN-LAST:event_jButtonUtilisateurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainIhm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainIhm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainIhm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainIhm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainIhm().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainIhm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonUtilisateur;
    private javax.swing.JButton jButton_Quitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_autre;
    private javax.swing.JLabel jLabel_cable;
    private javax.swing.JLabel jLabel_cpu;
    private javax.swing.JLabel jLabel_hdd;
    private javax.swing.JLabel jLabel_prixTotal;
    private javax.swing.JLabel jLabel_ram;
    // End of variables declaration//GEN-END:variables
}
